// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonteSeuCarro.Contexto;

#nullable disable

namespace MonteSeuCarro.Migrations
{
    [DbContext(typeof(ConcessionariaContext))]
    [Migration("20220809175529_opcionais")]
    partial class opcionais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.6.22329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MonteSeuCarro.Automovel.AdicionaisCarro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarroId")
                        .HasColumnType("int")
                        .HasColumnName("Carro Id");

                    b.Property<string>("OpcionaisCarros")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Opcionais");

                    b.HasKey("Id");

                    b.HasIndex("CarroId");

                    b.ToTable("Opcionais", (string)null);
                });

            modelBuilder.Entity("MonteSeuCarro.Automovel.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("Ano")
                        .HasColumnOrder(3);

                    b.Property<string>("CorDoCarro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cor")
                        .HasColumnOrder(4);

                    b.Property<string>("MarcaDoAutomovel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Marca")
                        .HasColumnOrder(1);

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Modelo")
                        .HasColumnOrder(2);

                    b.Property<int>("QntdPortas")
                        .HasColumnType("int")
                        .HasColumnName("Portas")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("MonteSeuCarro.Automovel.AdicionaisCarro", b =>
                {
                    b.HasOne("MonteSeuCarro.Automovel.Carro", "Carro")
                        .WithMany("Adicionais")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");
                });

            modelBuilder.Entity("MonteSeuCarro.Automovel.Carro", b =>
                {
                    b.Navigation("Adicionais");
                });
#pragma warning restore 612, 618
        }
    }
}
